import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faSpinner,
  faAngleRight,
  faAngleLeft,
  faCheck,
  faLock,
  faExclamation,
  faBars,
  faChevronLeft,
  faHeart,
  faEllipsisV,
  faArrowRight,
  faRedoAlt,
  faExclamationCircle,
  faEye,
  faEyeSlash, 
  faTimes,
  faCheckCircle,
  faAngleUp,
  faAngleDown,
  faUpload,
  faCopy
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faSpinner,
  faAngleLeft,
  faArrowRight,
  faAngleRight,
  faCheck,
  faLock,
  faExclamation,
  faBars,
  faChevronLeft,
  faHeart,
  faEllipsisV,
  faRedoAlt,
  faExclamationCircle,
  faEye,
  faEyeSlash,
  faTimes,
  faCheckCircle,
  faAngleUp,
  faAngleDown,
  faUpload,
  faCopy
);
